class netdata (
  $release_version =  '1.5.0',
  $config_dir =  '/etc/netdata',
  $config_file =  '/etc/netdata/netdata.conf',
  $manage_config =  true,
  $manage_firewall =  true,
  $manage_alarms =  true,
  $firewall_port =  19999,
  $custom_registry_enabled =  false,
  $custom_registry_hostname =  '~',
  $custom_registry_to_announce =  '~',
  $install_dependencies =  true,
  $install_plugin_dependencies =  true,
  $install_jq =  true,
  $install_dir_root =  '~',
  $installation_source =  'https://github.com/firehol/netdata.git',
  $repo_location =  '/opt/staging/netdata',
  $repo_ensure =  present,
  $service_enable =  true,
  $service_ensure =  running,
  $service_manage =  true,
  $service_name =  'netdata',
  $webserver_manage =  true,
  $webserver_class =  'nginx',
  $update_with_cron =  true,
  $update_cron_hour =  2,
  $update_cron_min =  30,
  $update_cron_user =  'root',
  $alarms_notify_config =  '/etc/netdata/health_alarm_notify.conf',
  $alarms_email =  false,
  $alarms_email_recipient =  'root',
  $alarms_pushover =  false,
  $alarms_pushover_recipient = undef ,
  $alarms_pushover_app_token = undef ,
  $alarms_pushbullet =  false,
  $alarms_pushbullet_access_token = undef ,
  $alarms_pushbullet_recipient = undef ,
  $alarms_twilio =  false,
  $alarms_twilio_account_sid = undef ,
  $alarms_twilio_account_token = undef ,
  $alarms_twilio_number = undef ,
  $alarms_twilio_recipient = undef ,
  $alarms_messagebird =  false,
  $alarms_messagebird_access_key = undef ,
  $alarms_messagebird_number = undef ,
  $alarms_messagebird_recipient = undef ,
  $alarms_telegram =  false,
  $alarms_telegram_bot_token = undef ,
  $alarms_telegram_recipient = undef ,
  $alarms_slack =  false,
  $alarms_slack_webhook_url = undef ,
  $alarms_slack_recipient = undef ,
  $alarms_discord =  false,
  $alarms_discord_webhook_url = undef ,
  $alarms_discord_recipient = undef ,
  $alarms_hipchat =  false,
  $alarms_hipchat_server =  'api.hipchat.com',
  $alarms_hipchat_auth_token = undef ,
  $alarms_hipchat_recipient = undef ,
  $alarms_kafka =  false,
  $alarms_kafka_url = undef ,
  $alarms_kafka_sender_ip = undef ,
  $alarms_pagerduty =  false,
  $alarms_pagerduty_recipient = undef ,
  $options,
  ) {

  contain netdata::install
  contain netdata::config
  contain netdata::service

  Class['::netdata::install'] ->
  Class['::netdata::config'] ~>
  Class['::netdata::service']
}
