class netdata (
  $release_version,
  $config_dir,
  $config_file,
  $firewall_port,
  $custom_registry_enabled,
  $custom_registry_hostname,
  $custom_registry_to_announce,
  $manage_config,
  $manage_firewall,
  $manage_alarms,
  $install_dependencies,
  $install_plugin_dependencies,
  $install_jq,
  $install_dir_root,
  $installation_source,
  $repo_location,
  $repo_ensure,
  $service_enable,
  $service_ensure,
  $service_manage,
  $service_name,
  $service_provider,
  $options,
  $alarms_notify_config,
  $alarms_email,
  $alarms_email_recipient,
  $alarms_pushover,
  $alarms_pushover_recipient,
  $alarms_pushover_app_token,
  $alarms_pushbullet,
  $alarms_pushbullet_access_token,
  $alarms_pushbullet_recipient,
  $alarms_twilio,
  $alarms_twilio_account_sid,
  $alarms_twilio_account_token,
  $alarms_twilio_number,
  $alarms_twilio_recipient,
  $alarms_messagebird,
  $alarms_messagebird_access_key,
  $alarms_messagebird_number,
  $alarms_messagebird_recipient,
  $alarms_telegram,
  $alarms_telegram_bot_token,
  $alarms_telegram_recipient,
  $alarms_slack,
  $alarms_slack_webhook_url,
  $alarms_slack_recipient,
  $alarms_discord,
  $alarms_discord_webhook_url,
  $alarms_discord_recipient,
  $alarms_hipchat,
  $alarms_hipchat_server,
  $alarms_hipchat_auth_token,
  $alarms_hipchat_recipient,
  $alarms_kafka,
  $alarms_kafka_url,
  $alarms_kafka_sender_ip,
  $alarms_pagerduty,
  $alarms_pagerduty_recipient,
  ) {

  contain netdata::install
  contain netdata::config
  contain netdata::service

  Class['::netdata::install'] ->
  Class['::netdata::config'] ~>
  Class['::netdata::service']
}
